services:
  - type: web
    name: todo
    env: node
    region: singapore
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
